### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by iltempo** [mehcode/oauth1-rs#6]
First of all, thank you for the crate. It helped me a lot connecting to Instapaper using OAuth 1.0a with XAuth.

Would you be so kind as to release a new version?  Unfortunately, the dependencies of 0.3.0 do not resolve anymore.

```
   Updating crates.io index
error: failed to select a version for the requirement `ring = "^0.12"`
  candidate versions found which didn't match: 0.14.0, 0.13.5, 0.8.1
  location searched: crates.io index
required by package `oauth1 v0.3.0`
```

I saw you making some compatibility changes that work with my code. Let me know if I can help out in any way.

Thanks!

**Comment by mehcode** [comment]
I don't use this crate myself anymore. I'll accept a dependency bump PR and push a release out though if you want to submit it. 

We should move off `ring` if anyone wants to make that effort but a bump should be enough for now.

**Comment by iltempo** [comment]
Thank you for being open to changes to the lib.

Gurpartap made the effort of bumping dependencies. I can confirm that it works well. Please merge #7 and release a new minor version.

Thank you.
